export const FORM_SET_VALUE: "FORM_SET_VALUE" = "FORM_SET_VALUE";

export const REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST" =
  "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS" =
  "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED: "REGISTER_USER_FAILED" =
  "REGISTER_USER_FAILED";

export const LOGIN_USER_SUBMIT: "LOGIN_USER_SUBMIT" = "LOGIN_USER_SUBMIT";
export const LOGIN_USER_SUBMIT_SUCCESS: "LOGIN_USER_SUBMIT_SUCCESS" =
  "LOGIN_USER_SUBMIT_SUCCESS";
export const LOGIN_USER_SUBMIT_FAILED: "LOGIN_USER_SUBMIT_FAILED" =
  "LOGIN_USER_SUBMIT_FAILED";

export const SET_AUTH_CHECKED: "SET_AUTH_CHECKED" = "SET_AUTH_CHECKED";
export const SET_USER: "SET_USER" = "SET_USER";

export const FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST" =
  "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS" =
  "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED" =
  "FORGOT_PASSWORD_FAILED";

export const CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST" =
  "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS" =
  "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED: "CHANGE_PASSWORD_FAILED" =
  "CHANGE_PASSWORD_FAILED";
