export const ORDER_PROFILE_CONNECT: "ORDER_PROFILE_CONNECT" =
  "ORDER_PROFILE_CONNECT";
export const ORDER_PROFILE_DISCONNECT: "ORDER_PROFILE_DISCONNECT" =
  "ORDER_PROFILE_DISCONNECT";
export const ORDER_PROFILE_WS_CONNECTING: "ORDER_PROFILE_WS_CONNECTING" =
  "ORDER_PROFILE_WS_CONNECTING";
export const ORDER_PROFILE_WS_OPEN: "ORDER_PROFILE_WS_OPEN" =
  "ORDER_PROFILE_WS_OPEN";
export const ORDER_PROFILE_WS_CLOSE: "ORDER_PROFILE_WS_CLOSE" =
  "ORDER_PROFILE_WS_CLOSE";
export const ORDER_PROFILE_WS_MESSAGE: "ORDER_PROFILE_WS_MESSAGE" =
  "ORDER_PROFILE_WS_MESSAGE";
export const ORDER_PROFILE_WS_ERROR: "ORDER_PROFILE_WS_ERROR" =
  "ORDER_PROFILE_WS_ERROR";
